### ISSUE TITLE
Need help building this

### ISSUE THREAD

**Issue by c094728** [oxygenxml/oxygen-cmis-plugin#2]
I pulled down the project and ran
mvn clean install
It failed to find dependencies for oxygen xml com.oxygenxml:oxygen-sdk:22.0-SNAPSHOT
I changed the version to use 21.1.0.2 to resolve that.  
And also had to add a version to com.github.eirslett:frontend-maven-plugin
It seems to have build successfully but a few tests are getting errors.  Plus there are a lot of warnings.   I attached the log.  Is this project set up correctly to build from master?
[build.log](https://github.com/oxygenxml/oxygen-cmis-plugin/files/3649022/build.log)

**Comment by ctalau** [comment]
The project is meant to be built from `BRANCH_OXYGEN_RELEASE_21_1`. `master` contains a version that will work with the next release of Oxygen (version 22) and cannot be built with public artifacts.

To build it, from the 21.1 branch you should run:

```
mvn clean install -Doxygen.version=21.1.0.0
```
